urls.py
from django.conf.urls.defaults import patterns, include, url
#from voip import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'voipdb.views.home', name='home'),
    # url(r'^voipdb/', include('voipdb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('voip.urls')),

#    # ex: /
#    url(r'^$', views.index, name='index'),
#    # ex: /
#    #url(r'^login$', views.login_user, name='login_user'),
#
#    url(r'^login/$', 'django.contrib.auth.views.login', {
#      'template_name': 'voip/templates/voip/login.html'
#    }),
#    url(r'^logout/$', 'django.contrib.auth.views.logout', {
#      #'template_name': 'admin/login.html'
#    }),
#
#    # ex: /extensions/
#    url(r'^extensions/$', views.extension_show, name='extension_show'),
#
#    # ex: /extensions/5/edit/
#    url(r'^extensions/(?P<extension_id>\d+)/edit/$', views.extension_edit, name='extension_edit'),
#
#    # ex: /polls/5/vote/
##    url(r'^(?P<member_id>\d+)/vote/$', views.vote, name='vote'),
)

voip/urls.py
from django.conf.urls.defaults import patterns, include, url
from voip import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'voipdb.views.home', name='home'),
    # url(r'^voipdb/', include('voipdb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
#    url(r'^admin/', include(admin.site.urls)),

    # ex: /
    url(r'^$', views.index, name='index'),

    # ex: /userinfo/
    url(r'^userinfo/$', views.userinfo, name='userinfo'),

    # ex: /phonebook/
    url(r'^phonebook/$', views.phonebook, name='phonebook'),

    # ex: /login/
    #url(r'^login/$', views.login_user, name='login_user'),

    url(r'^login/$', 'django.contrib.auth.views.login', {
      'template_name': 'voip/login.html'
    }),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {
      #'template_name': 'voip/logout.html'
    }),

    # ex: /extensions/
    url(r'^extensions/$', views.extensions_show, name='extensions_show'),

    # ex: /extensions/5/add/
    url(r'^extensions/add/$', views.extension_add, name='extension_add'),

    # ex: /extensions/5/edit/
    url(r'^extensions/(?P<extension_id>\d+)/edit/$', views.extension_edit, name='extension_edit'),

    # ex: /extensions/5/delete/
    url(r'^extensions/(?P<extension_id>\d+)/delete/$', views.extension_delete, name='extension_delete'),

    # ex: /sipuser/5/add/
    url(r'^sipuser/(?P<extension_id>\d+)/add/$', views.sipuser_add, name='sipuser_add'),

    # ex: /sipuser/5/edit/
    url(r'^sipuser/(?P<sipuser_id>\d+)/edit/$', views.sipuser_edit, name='sipuser_edit'),

    # ex: /sipuser/5/delete/
    url(r'^sipuser/(?P<sipuser_id>\d+)/delete/$', views.sipuser_delete, name='sipuser_delete'),

)

voip/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save

from datetime import datetime

class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)
    # Other fields here
    uid = models.CharField(max_length=254)
    cn = models.CharField(max_length=254)
    sn = models.CharField(max_length=254)
    givenName = models.CharField(max_length=254)
    userPassword = models.CharField(max_length=254)
    shadowLastChange = models.IntegerField(null=True)
    shadowMax = models.IntegerField(null=True)
    shadowWarning = models.IntegerField(null=True)
    loginShell = models.CharField(max_length=254)
    uidNumber = models.IntegerField(null=True)
    gidNumber = models.IntegerField(null=True)
    homeDirectory = models.CharField(max_length=254)
    gecos = models.CharField(max_length=254)
    mail = models.EmailField(max_length=254)
    l = models.CharField(max_length=254)
    telephoneNumber = models.CharField(max_length=254)
    created = models.DateTimeField('date created',default=datetime.now())
    changed = models.DateTimeField('date changed')

def create_user_profile(sender, instance, created, **kwargs):
    #if created:
    #    UserProfile.objects.create(user=instance)
    UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)

class members(models.Model):
    # First things first - wherever you have a model with a primary key named "id", just delete it.
    # Django already assumes that your table has an "id" column and defaults to an automatic primary key field - you don't need to define it in the class.
    # id = models.IntegerField(primary_key=True)
    nickname = models.CharField(max_length=100,unique=True)
    password = models.CharField(max_length=255)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    street = models.CharField(max_length=255)
    housenumber = models.CharField(max_length=10)
    zip = models.CharField(max_length=10)
    town = models.CharField(max_length=255)
    telephone = models.CharField(max_length=25)
    mobilephone = models.CharField(max_length=25)
    fax = models.CharField(max_length=25)
    email = models.CharField(max_length=50)
    homepage = models.CharField(max_length=50)
    created = models.DateTimeField('date created')
    changed = models.DateTimeField('date changed')
    mentor_id = models.IntegerField(default=0)
    instant_messenger_nick = models.CharField(max_length=50)
    def __unicode__(self):
        return u'%s' % (self.nickname)
    def check_password(self, password):
        return True
    class Meta:
        db_table = "members"
        verbose_name = "member"
        verbose_name_plural = "members"

class extensions(models.Model):
    # First things first - wherever you have a model with a primary key named "id", just delete it.
    # Django already assumes that your table has an "id" column and defaults to an automatic primary key field - you don't need to define it in the class.
    # id = models.IntegerField(primary_key=True)
    extension = models.CharField(max_length=10,unique=True)
    potsnumber = models.CharField(max_length=50,unique=True)
    voicemail = models.BooleanField(default=False)
    voicemail_pin = models.CharField(max_length=4,null=True)
    voicemail_emailnotify = models.BooleanField(default=False)
    voicemail_emailnotify_attach = models.BooleanField(default=False)
    voicemail_delay = models.IntegerField(default=15)
    voicemail_emailnotify = models.BooleanField(default=False)
    meetme = models.BooleanField(default=False)
    meetme_pin = models.CharField(max_length=4,null=True)
    meetme_admin_pin = models.CharField(max_length=4,null=True)
    h323 = models.NullBooleanField(default=False)
    h323_ip = models.CharField(max_length=15,null=True)
    phonebook = models.NullBooleanField(default=True)
    id_members = models.ForeignKey(members,null=True,db_column="id_members")
    redirect_delay = models.IntegerField(default=0,null=True)
    redirect_target = models.CharField(max_length=32,null=True)
    redirect = models.BooleanField(default=False)
    fax = models.BooleanField(default=False)
    fax_email = models.CharField(max_length=100,null=True)
    created = models.DateTimeField('date created')
    changed = models.DateTimeField('date changed')
    def __unicode__(self):
        return u'%s' % (self.extension)
    class Meta:
        verbose_name = "extension"
        verbose_name_plural = "extensions"
#    def save(self):
#        if not self.id:
#            self.voicemail = self.voicemail
#            self.voicemail_pin = self.voicemail_pin
#        self.voicemail_delay = self.voicemail_delay
#        super(extensions, self).save()

class sip(models.Model):
    # First things first - wherever you have a model with a primary key named "id", just delete it.
    # Django already assumes that your table has an "id" column and defaults to an automatic primary key field - you don't need to define it in the class.
    # id = models.IntegerField(primary_key=True)
    secret = models.CharField(max_length=50)
    nat = models.BooleanField(default=True)
    dtmfmode = models.CharField(max_length=25,null=True,default="rfc2833")
    port = models.IntegerField()
    provider = models.BooleanField(default=False)
    provider_host = models.CharField(max_length=255,null=True)
    provider_fromuser = models.CharField(max_length=255,null=True)
    provider_fromdomain = models.CharField(max_length=255,null=True)
    provider_secret = models.CharField(max_length=50,null=True)
    id_voip_extensions = models.ForeignKey(extensions,null=True,db_column="id_voip_extensions")
    alt_sip_username = models.CharField(max_length=50,null=True)
    alt_accountcode = models.CharField(max_length=200,null=True)
    calleridnum = models.CharField(max_length=32,null=True)
    calleridtext = models.CharField(max_length=50,null=True)
    created = models.DateTimeField('date created')
    changed = models.DateTimeField('date changed')
    def __unicode__(self):
        return u'%s' % (self.id)
    class Meta:
        verbose_name_plural = "sip"
        ordering = ['id']

class astrt_sipusers(models.Model):
    # id = models.IntegerField()
    # Error: One or more models did not validate:
    # voip.astrt_sipusers: "id": You can't use "id" as a field name, because each model automatically gets an "id" field if none of the fields have primary_key=True. You need to either remove/rename your "id" field or add primary_key=True to a field.
    name = models.CharField(max_length=80)
    accountcode = models.CharField(max_length=20, null=True)
    amaflags = models.CharField(max_length=7, null=True)
    callgroup = models.CharField(max_length=10, null=True)
    callerid = models.CharField(max_length=80, null=True)
    canreinvite = models.CharField(max_length=3, default="yes", null=True)
    context = models.CharField(max_length=80, null=True)
    defaultip = models.CharField(max_length=45, null=True)
    dtmfmode = models.CharField(max_length=7, null=True)
    fromuser = models.CharField(max_length=80, null=True)
    fromdomain = models.CharField(max_length=80, null=True)
    host = models.CharField(max_length=31, default="")
    insecure = models.CharField(max_length=4, null=True)
    language = models.CharField(max_length=2, null=True)
    mailbox = models.CharField(max_length=50, null=True)
    md5secret = models.CharField(max_length=80, null=True)
    nat = models.CharField(max_length=29, default="")
    permit = models.CharField(max_length=95, null=True)
    deny = models.CharField(max_length=95, null=True)
    mask = models.CharField(max_length=95, null=True)
    pickupgroup = models.CharField(max_length=10, null=True)
    port = models.CharField(max_length=5, default="")
    qualify = models.CharField(max_length=3, null=True)
    restrictcid = models.CharField(max_length=1, null=True)
    rtptimeout = models.CharField(max_length=3, null=True)
    rtpholdtimeout = models.CharField(max_length=3, null=True)
    secret = models.CharField(max_length=80, null=True)
    type = models.CharField(max_length=10, default="friend") # no max_length defined in db?
    username = models.CharField(max_length=80, default="")
    allow = models.CharField(max_length=200, default="!all,g729,ilbc,gsm,ulaw,alaw", null=True)
    musiconhold = models.CharField(max_length=100, null=True)
    regseconds = models.BigIntegerField(default="0")
    ipaddr = models.CharField(max_length=45, default="")
    regexten = models.CharField(max_length=80, default="")
    cancallforward = models.CharField(max_length=3, default="yes", null=True)
    lastms = models.IntegerField(default=0)
    defaultuser = models.CharField(max_length=80, null=True)
    fullcontact = models.CharField(max_length=160, null=True)
    regserver = models.CharField(max_length=30, null=True)
    useragent = models.CharField(max_length=100, null=True)
    callbackextension = models.CharField(max_length=40, null=True)
    # phonenumberid = models.BigIntegerField()
    phonenumberid = models.ForeignKey(extensions,null=True,db_column="phonenumberid")
    outbound_phonenumberid = models.BigIntegerField(default=1)
    created = models.DateTimeField('date created')
    changed = models.DateTimeField('date changed')
    comment = models.CharField(max_length=160, null=True)
    class Meta:
        db_table = "astrt_sipusers"

voip/forms.py
from django import forms

class ExtensionEditForm(forms.Form):
    voicemail = forms.BooleanField(label='Voicemail', required=False)
    voicemail_pin = forms.CharField(label='Voicemail PIN', min_length=4, max_length=4)
    voicemail_delay = forms.IntegerField(label='Voicemail Delay', min_value=1, max_value=999)
    voicemail_emailnotify = forms.BooleanField(label='E-Mail Notify', required=False)
    phonebook = forms.BooleanField(label='Telefonbuch', required=False)

class SipuserEditForm(forms.Form):
    reset_pw = forms.BooleanField(label='Reset Password', required=False, )
    #secret = forms.CharField(label='Passwort', min_length=16, max_length=16)
    nat = forms.BooleanField(label='NAT', required=False, )
    CHOICES = (
        ('auto', 'Auto'),
        ('inband', 'Inband'),
        ('rfc2833', 'RFC2833'),
        ('info','INFO'),
    )
    dtmfmode = forms.ChoiceField(choices=CHOICES, required=True, label='DTMF Mode')
    comment = forms.CharField(label='Kommentar', required=False, min_length=0, max_length=160)

voip/templates/voip/base.html
{% autoescape on %}{% load static %}<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<link rel="icon" type="image/x-icon" href="{% get_static_prefix %}voip/faviconF.ico">
	<link rel="stylesheet" type="text/css" href="{% get_static_prefix %}voip/main.css" />
	<script language="JavaScript" src="{% get_static_prefix %}voip/main.js"></script>
        <!-- django: how to load following js only when page(e.g. phonebook) needs it? -->
	<script src="{% get_static_prefix %}voip/jquery-1.11.1.min.js"></script>
	<script src="{% get_static_prefix %}voip/tablesorter/jquery.tablesorter.js"></script>
	<title>Funkfeuer VoIP - {% block title %}Funkfeuer VoIP Database Frontend{% endblock %}</title>
</head>
<body>
{% if request.user %}
	<div id="menu">
		<a href="/">Hauptseite</a> | <a href="/userinfo/">Benutzerdaten</a> | <a href="https://marvin.funkfeuer.at/frontend_wien/index.php?section=nodes&id_members={{ member.id }}">Nodes</a> | <a href="/extensions/">VoIP</a> | <a href="/phonebook/">Phonebook</a>  | <a href="/logout/">Logoff</a>
	</div>
        <div style="position:absolute; top:0px; right:0px; width:400px; height:70px;"><img src="{% get_static_prefix %}voip/img/headerff.jpg" width="400px"; height="70px"></div>
	<hr/>
{% endif %}
{% block content %}{% endblock %}
	<div class=footer><b>&copy;{% now "Y" %} <a href="https://github.com/vchrizz/voipdb">Funkfeuer VoIPdb Webfrontend</a></b> (fork from <a href="http://sourceforge.net/p/redeemer">redeemer.frontend</a> + <a href="https://gitorious.org/0xff_frontend/frontend">0xff mods</a>)</div>
</body>
</html>
{% endautoescape %}

voip/templates/voip/extension_edit.html
{% extends "voip/base.html" %}{% block title %}Extension edit{% endblock %}{% block content %}{% if form.errors %}{{ form.errors }}{% endif %}
	<form action="." method="post" name="update_voip_form" onsubmit="return verifyForm(this);">
	{% csrf_token %}
	<table>
		<tr>
			<th align="right" valign="top">Voicemail</th>
			<td>{{ form.voicemail }}</td>
		</tr>
		<tr>
			<th align="right" valign="top">Voicemail PIN</th>
			<td>{{ form.voicemail_pin }}</td>
		</tr>
		<tr>
			<th align="right" valign="top">Voicemail Delay</th>
			<td>{{ form.voicemail_delay }}</td>
		</tr>
		<tr>
			<th align="right" valign="top">E-Mail Notify</th>
			<td>{{ form.voicemail_emailnotify }}</td>
		</tr>
		<tr>
			<th align="right" valign="top">Telefonbuch</th>
			<td>{{ form.phonebook }}</td>
		</tr>
		<tr>
			<th align="right" valign="top">&nbsp;</th>
			<td><input type="submit" name="submit" value="&Auml;ndern" /></td>
		</tr>
	</table>
	</form>
{% endblock %}

voip/templates/voip/extensions.html
{% extends "voip/base.html" %}{% block title %}Extensions{% endblock %}{% block content %}{% if form.errors %}{{ form.errors }}{% endif %}
	<br>
	<caption>VoIP [<a href="{% url extension_add %}">hinzuf&uuml;gen</a>]</caption>
        {% if error %}<ul><li>{{ error }}</ul>{% endif %}
        <form action="." method="post" name="update_voip_sip_form" onsubmit="return verifyForm(this);">
        {% csrf_token %}
        <table>
	<thead>
		<tr>
		<th>Durchwahl</th>
		<th>Voicemail</th>
		<th>Voicemail PIN</th>
		<th>Voicemail Delay</th>
		<th>E-Mail Notify</th>
		<th>Telefonbuch</th>
<!--		<th>Erstellt</th>
		<th>Ge&auml;ndert</th>-->
		<th>L&ouml;schen</th>
		</tr>
	</thead>
	<tbody>
	{% for extension in extension_list %}
	<tr>
		<td rowspan="2"><a href="{% url extension_edit extension.id %}" style="font-size:1.5em">{{ extension.extension }}</a></td>
		<td><center>{{ extension.voicemail }}</center></td>
		<td><center>{{ extension.voicemail_pin }}</center></td>
		<td><center>{{ extension.voicemail_delay }}</center></td>
		<td><center>{{ extension.voicemail_emailnotify }}</center></td>
		<td><center>{{ extension.phonebook }}</center></td>
<!--		<td><center>{{ extension.created }}</center></td>
		<td><center>{{ extension.changed }}</center></td>-->
		<td><center><a href="{% url extension_delete extension.id %}" onclick="return askDelete()">X</a></center></td>
		</tr>
		<tr>
			<td colspan="9" style="background-color:#e8e8e8">
			<table>
			<tr>
				<th>Login</th>
				<th>Passwort</th>
				<th>NAT</th>
				<th>DTMF Modus</th>
				<th>IP-Addresse</th>
				<th>Lastseen</th>
				<th>UserAgent</th>
<!--				<th>Erstellt</th>
				<th>Ge&auml;ndert</th>-->
				<th>Kommentar</th>
				<th>L&ouml;schen</th>
			</tr>
			{% for sipuser in extension.astrt_sipusers_set.all %}
			<tr>
				<td><a href="{% url sipuser_edit sipuser.id %}">{{ request.user.username }}_{{ sipuser.id }}</a></td>
				<td>{{ sipuser.secret }}</td>
				<td><center>{{ sipuser.nat }}</center></td>
				<td><center>{{ sipuser.dtmfmode }}</center></td>
				<td><center>{{ sipuser.ipaddr }}</center></td>
				<td><center>{{ sipuser.lastms }}ms</center></td>
				<td><center>{{ sipuser.useragent }}</center></td>
<!--				<td><center>{{ sipuser.created }}</center></td>
				<td><center>{{ sipuser.changed }}</center></td>-->
				<td><center>{{ sipuser.comment }}</center></td>
				<td><center><a href="{% url sipuser_delete sipuser.id %}" onclick="return askDelete()">X</a></center></td>
			</tr>
			{% endfor %}
			</table>
			<a href="{% url sipuser_add extension.id %}">add sip device</a>
			</td>
	</tr>
	{% endfor %}
	</tbody>
	</table>

	<table class=help>
	<tr>
		<th>Hilfe zur Einrichtung</th>
		<th>Hilfe zur Konfiguration</th>
		<th>Einwahlnummern</th>
	</tr>
	<tr>
		<td style="width: 300px; text-align: left; vertical-align: top; padding: 15px">
			<li>Jede Durchwahl muss zumindest ein 'SIP Device'(=Anmeldung) eingericht haben.
			<li>Zum Anlegen einer Durchwahl auf 'hinzuf&uuml;gen' klicken, danach auf 'add sip device' klicken.
			<li>Jeder Apparat, Softwareclient oder Gateway braucht sein eigenes 'SIP-Device'.
		</td>
		<td style="width: 300px; text-align: left; vertical-align: top; padding: 15px">
			<li>SIP-Server: voip.funkfeuer.at
			<li>Port: 5060
			<li>User-ID: (siehe 'SIP-Devices')
			<li>Passwort: (siehe 'SIP-Devices')
			<br><br><b>Optionale Parameter:</b>
			<li>Preffered Codec: G711a
			<li>Register: YES
			<li>NAT: YES
			<li>STUN-Server: stun.funkfeuer.at
		</td>
		<td style="width: 300px; text-align: left; vertical-align: top; padding: 15px">
			<li>Intern: <b>xxxx</b>
			<li>Extern:<br><b>01 / 2360933 - xxxx</b><br><b>0720 / 550933 - xxxx</b> 
			<li>optional ENUM:<br><b>0780 / 700888 - xxxx</b>
			<!-- <li>Festnetz/Mobil: <b>01 / 302555 - xxx</b> (exprimentell) -->
		</td>
	</tr>
	</table>

	<div style="padding: 15px; margin: 20px; border: 1px solid red; background-color: #ffcccc; font-weight: bold; display: block; width: 600px;">
	Das VOIP Service ist nicht f&uuml;r Notrufe oder andere lebenswichtige Services geeignet. 
	<p>
	Jeder Benutzer muss dieser Einschr&auml;nkung zustimmen, oder darf andernfalls das Service nicht nutzen.
	</div>
{% endblock %}

voip/templates/voip/index.html
{% extends "voip/base.html" %}{% block title %}Willkommen{% endblock %}{% block content %}
	Willkommen im VoIP Frontend ...
	<br>
	<div style="padding: 15px; margin: 20px; border: 1px solid lightblue; background-color: #55aaff; font-weight: bold; display: block; width: 600px;">
		Feature-Requests: (sind gerne gesehen auf <a href="mailto:voip-dev@lists.funkfeuer.at?subject=Feature-Request">voip-dev@lists.funkfeuer.at</a>)
		<ul>
			<li>ausgehende Anrufe (momentan evtl. nur anonym machbar)
			<li>neue HTML-Templates bzw. neues Design?
		</ul>
		<br>
		ToDo: {{ foo }}
		<ul>
		</ul>
	</div>
{% endblock %}

voip/templates/voip/login.html
{% extends "voip/base.html" %}{% block title %}Login{% endblock %}{% block content %}{% load static %}
<center>
{% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{{ state }}
<form action="." method="post" >
{% csrf_token %}
{% if next %}
<input type="hidden" name="next" value="{{ next }}" />
{% endif %}
<table>
 <tr>
  <td rowspan="3" style="background-color:#fff; width:108px; height:80px;"><img src="{% get_static_prefix %}voip/img/OxFF_and_character.jpg" width="108px" height="80px"></td>
  <th align="right" valign="top">Nickname</th>
  <td>
   <input type="text" name="username" size="20" value="{{ username }}" />
  </td>
  <td rowspan="3" style="background-color:#fff; width:205px; height:64px;"><img src="{% get_static_prefix %}voip/img/logo_mascotte.jpg" width="205px" height="64px"></td>
 </tr>
 <tr>
  <th align="right" valign="top">Passwort</th>
  <td>
   <input type="password" name="password" size="20" value="" />
  </td>
 </tr>
 <tr>
  <th align="right" valign="top">&nbsp;</th>
  <td>
   <input type="submit" name="submit" value="Login" />
  </td>
 </tr>
</table>
{% comment %}
<input type="hidden" name="_fields" value="nickname:password:submit" />
{% endcomment %}
</form>

 <br>
			<a href="https://marvin.funkfeuer.at/frontend_wien/index.php?section=pwdreset">forgot your password?</a>  

 <br>

<div style="padding: 15px; margin: 20px; border: 1px solid red; background-color: #ffcccc; font-weight: bold; display: block; width: 600px;">
Das VOIP Service ist nicht f&uuml;r Notrufe oder andere lebenswichtige Services geeignet. 
<p>
Jeder Benutzer muss dieser Einschr&auml;nkung zustimmen, oder darf andernfalls das Service nicht nutzen.
Mit dem Login wird dies als gelesen und verstanden akzeptiert.
</div>

</center>

{% endblock %}

voip/templates/voip/phonebook.html
{% extends "voip/base.html" %}{% block title %}Telefonbuch{% endblock %}{% block content %}
	<script>
	$(document).ready(function() { 
		// call the tablesorter plugin 
		$("table").tablesorter({ 
			// sort on the third column, order asc 
			sortList: [[0,0]] 
		}); 
	});
	</script>
	<caption>"Live"-Telefonbuch (Tabelle sortierbar)</caption>
	<table class="tablesorter">
	<thead>
	<tr>
		<th>Durchwahl</th>
		<th>Vorname</th>
		<th>Nachname</th>
		<th>Nickname</th>
		<th>Online Devices</th>
	</tr>
	</thead>
	<tbody>
	{% for extension in extension_list %}
	<tr>
		<td style="text-align:center;">{{ extension.extension }}</td>
		<td>{{ extension.id_members.firstname }}</td>
		<td>{{ extension.id_members.lastname }}</td>
		<td>{{ extension.id_members.nickname }}</td>
		<td>{% for sipuser in extension.astrt_sipusers_set.all %}{% if sipuser.lastms > 0 %}
		{{ sipuser.name }} lastseen:{{ sipuser.lastms }}ms{% endif %}{% endfor %}
		</td>
	</tr>
	{% endfor %}
	</tbody>
	</table>
{% endblock %}

voip/templates/voip/sipuser_edit.html
{% extends "voip/base.html" %}{% block title %}Sipuser edit{% endblock %}{% block content %}{% if form.errors %}{{ form.errors }}{% endif %}
        <form action="." method="post" name="update_voip_sip_form" onsubmit="return verifyForm(this);">
        {% csrf_token %}
        <table>
                <tr>
                        <th align="right" valign="top">Passwort<br><input type="checkbox" name="reset_pw" />reset</th>
                        <td>{{ sipuser.secret }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">UserAgent</th>
                        <td>{{ sipuser.useragent }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">IP-Adresse</th>
                        <td>{{ sipuser.ipaddr }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">Lastseen</th>
                        <td>{{ sipuser.lastms }}ms</td>
                </tr>
                <tr>
                        <th align="right" valign="top">NAT</th>
                        <td>{{ form.nat }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">DTMF Modus</th>
                        <td>{{ form.dtmfmode }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">Kommentar</th>
                        <td>{{ form.comment }}</td>
                </tr>
                <tr>
                        <th align="right" valign="top">&nbsp;</th>
                        <td><input type="submit" name="submit" value="&Auml;ndern" /></td>
                </tr>
        </table>
        </form>
{% endblock %}